#
# Archivo de configuración de Travis.
# Proyecto Lovelace.
#

language: perl
perl:
 - "5.24"

# Instalación de dependencias
install:
  - sudo apt-get update
  - sudo apt-get install
    texlive
    texlive-latex-recommended
    texlive-latex-extra
    texlive-lang-spanish
    texlive-bibtex-extra
    texlive-generic-extra
    doxygen
    graphviz
  # Instalación de paquetes directo desde el CTAN y sourceforge
  # glossaries
  - wget http://mirrors.ctan.org/install/macros/latex/contrib/glossaries.tds.zip
  - unzip -d ~/texmf glossaries.tds.zip
  # tracklang
  - wget http://mirrors.ctan.org/install/macros/generic/tracklang.tds.zip
  - unzip -d ~/texmf tracklang.tds.zip
  # bibtex
  - wget https://sourceforge.net/projects/biblatex/files/biblatex-3.9/biblatex-3.9.tds.tgz
  - tar -xvf biblatex-3.9.tds.tgz -C ~/texmf
  # babel
  - wget http://mirrors.ctan.org/install/macros/latex/required/babel-base.tds.zip
  - unzip -d ~/texmf babel-base.tds.zip
  # biber
  - wget https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.10/biblatex-biber.tar.gz
  - mkdir ~/ejecutable_biber
  - tar -xvf biblatex-biber.tar.gz -C ~/ejecutable_biber
  - export PATH=~/ejecutable_biber/biblatex-biber-2.10/bin/:$PATH
  # No pues sí... lo único que tienen que hacer los gestores de paquetes de las
  # distribuciones es descomprimir un zip en la carpeta de latex.
  # ¿Para qué tantos intermediarios?
  # # Instalación de cryptopp
  # - wget https://cryptopp.com/cryptopp600.zip
  # - unzip -a -d cryptopp cryptopp600.zip
  # - make -C cryptopp
  # - sudo mkdir /usr/include/cryptopp
  # - sudo mv cryptopp/*.h /usr/include/cryptopp/
  # - sudo mv cryptopp/libcryptopp.a /usr/lib/
  # # Instlación de openssl
  # - wget https://www.openssl.org/source/openssl-1.1.1-pre1.tar.gz
  # - tar -xvf openssl-1.1.1-pre1.tar.gz
  # - cd openssl-1.1.1-pre1 && ./config && make && make install && cd ..

# Fase de construcción
script:

  # Compilación de archivos de LaTeX
  # Esto debería dejar el pdf completo
  - make -B -C documentos_entregables
  - make -B -C documentos_entregables glosarios
  - make -B -C documentos_entregables referencias
  - make -B -C documentos_entregables
  - make -B -C documentos_entregables

  # Revisión de ortografía
  #  - make -C documentos_entregables ortografía

  # Ejecución de funciones de prueba
  # - make -C pruebas_librerias
  # - make -C pruebas_librerias correr

  # Documentación.
  - doxygen .doxygen
