#
# Archivo de configuración de Travis.
# Proyecto Lovelace.
#

# Configuración general #######################################################

language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        mariadb: '10.1'
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# Determinan el entorno: ubuntu trusty (14.04)
sudo: required
dist: trusty

#cache:
#  directories:
#    # Generales
#    - ~/texmf
#    # Texlive
#    - /usr/share/bug/texlive
#    - /usr/share/doc/texlive

# Instalación de dependencias #################################################
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get -qq install
    texlive
    texlive-latex-recommended
    texlive-latex-extra
    texlive-lang-spanish
    texlive-bibtex-extra
    texlive-generic-extra
    doxygen
    graphviz
    libmysqlcppconn-dev
  # glossaries
  - wget --quiet http://mirrors.ctan.org/install/macros/latex/contrib/glossaries.tds.zip
  - unzip --qq -d ~/texmf glossaries.tds.zip
  - rm glossaries.tds.zip
  # tracklang
  - wget --quiet http://mirrors.ctan.org/install/macros/generic/tracklang.tds.zip
  - unzip -qq -d ~/texmf tracklang.tds.zip
  - rm tracklang.tds.zip
  # bibtex
  - wget --quiet https://newcontinuum.dl.sourceforge.net/project/biblatex/biblatex-3.9/biblatex-3.9.tds.tgz
  - tar -xf biblatex-3.9.tds.tgz -C ~/texmf
  - rm biblatex-3.9.tds.tgz
  # babel
  - wget --quiet http://mirrors.ctan.org/install/macros/latex/required/babel-base.tds.zip
  - unzip -qq -d ~/texmf babel-base.tds.zip
  - rm babel-base.tds.zip
  # biber
  - wget --quiet https://phoenixnap.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz
  - mkdir ~/ejecutable_biber
  - tar -xf biber-linux_x86_64.tar.gz -C ~/ejecutable_biber
  - export PATH=~/ejecutable_biber/:$PATH
  - rm biber-linux_x86_64.tar.gz
  # Cryptopp
  - wget --quiet https://cryptopp.com/cryptopp600.zip
  - unzip --qq -a -d cryptopp cryptopp600.zip
  - make -C cryptopp
  - sudo mkdir /usr/include/cryptopp
  - sudo mv cryptopp/*.h /usr/include/cryptopp/
  - sudo mv cryptopp/libcryptopp.a /usr/lib/

install:
  - eval "${MATRIX_EVAL}"
  - make -C pruebas_librerias
  - make -C implementaciones
  - make -C implementaciones binarios/lovelace
  - make -C utilidades
  - cd bases_de_datos
  - chmod 770 crear_base.sh
  - chmod 770 crear_estructura.sh
  - sudo ./crear_base.sh
  - ./crear_estructura.sh
  - cd ..

script:
  - eval "${MATRIX_EVAL}"
# - make -C pruebas_librerias correr
  - make -C implementaciones correr
  - make -C utilidades correr
  - cd implementaciones
  - chmod 770 lovelace_prueba.sh
  - ./lovelace_prueba 100
  - cd ..

# Generación de documentación #################################################
after_success:
  # Compilación de archivos de LaTeX
  - make -B -C documentos_entregables
  - make -B -C documentos_entregables presentacion_fpe
  - make -B -C documentos_entregables referencias_fpe
  - make -B -C documentos_entregables presentacion_fpe
  - make -B -C documentos_entregables presentacion_fpe
  # Documentación.
  - make documentación_doxygen
  - make -C pagina_publica/documentacion_doxygen/latex

# Despliegue #################################################################
# Antes del despliegue
before_deploy:
  - mv README.md pagina_publica/
  - mv reglas_de_estilo.md pagina_publica/
  - mkdir -p pagina_publica/documentos_entregables/reporte_tecnico
  - mv documentos_entregables/reporte_tecnico/reporte_tecnico.pdf
    pagina_publica/documentos_entregables/reporte_tecnico/
  - mkdir -p pagina_publica/documentos_entregables/presentacion_fpe
  - mv documentos_entregables/presentacion_fpe/presentacion_fpe.pdf
    pagina_publica/documentos_entregables/presentacion_fpe/

# Fase de despliegue
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: pagina_publica
  keep-history: true
  name: RQF7_bot
  verbose: true
  on:
    branch: master
