#
# Archivo de configuración de Travis.
# Proyecto Lovelace.
#

# Instalación de dependencias
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
    texlive
    texlive-latex-recommended
    texlive-latex-extra
    texlive-lang-spanish
    texlive-bibtex-extra
    biber

# Fase de construcción
script:
  - make -C documentos_entregables
#  - make -C documentos_entregables referencias
#  - make -C documentos_entregables
