#
# Archivo de configuración de Travis.
# Proyecto Lovelace.
#

# Instalación de dependencias
install:
  - sudo apt-get update
  - sudo apt-get install
    texlive
    texlive-latex-recommended
    texlive-latex-extra
    texlive-lang-spanish
    texlive-bibtex-extra
    texlive-generic-extra
#    hunspell
#    myspell-es

  # Instalación de paquetes directo desde el CTAN y sourceforge
  # glossaries
  - wget http://mirrors.ctan.org/install/macros/latex/contrib/glossaries.tds.zip
  - unzip -d ~/texmf glossaries.tds.zip
  # tracklang
  - wget http://mirrors.ctan.org/install/macros/generic/tracklang.tds.zip
  - unzip -d ~/texmf tracklang.tds.zip
  # bibtex
  - wget https://sourceforge.net/projects/biblatex/files/biblatex-3.9/biblatex-3.9.tds.tgz
  - tar -xvf biblatex-3.9.tds.tgz -C ~/texmf
  # babel
  - wget http://mirrors.ctan.org/install/macros/latex/required/babel-base.tds.zip
  - unzip -d ~/texmf babel-base.tds.zip
  # biber
  - wget https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz
  - mkdir ~/ejecutable_biber
  - tar -xvf biber-linux_x86_64.tar.gz -C ~/ejecutable_biber
  - export PATH=~/ejecutable_biber/:$PATH

  # No pues sí... lo único que tienen que hacer los gestores de paquetes de las
  # distribuciones es descomprimir un zip en la carpeta de latex.
  # ¿Para qué tantos intermediarios?

# Fase de construcción
script:

  # Compilación de archivos de LaTeX
  # Esto debería dejar el pdf completo
  - make -C documentos_entregables
  - make -C documentos_entregables glosarios
  - make -C documentos_entregables referencias
  - make -C documentos_entregables
  - make -C documentos_entregables

  # Revisión de ortografía
#  - make -C documentos_entregables ortografía
