#
# Archivo de configuración de Travis.
# Proyecto Lovelace.
#

# Configuración general #######################################################

language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        mariadb: '10.1'
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# Determinan el entorno: ubuntu trusty (14.04)
sudo: required
dist: trusty

# Directorios/caché
cache:
  directories:
  - "cryptopp"
  - "entorno_virtual"
  - "~/texmf"

# Instalación de dependencias #################################################
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-get -qq update
  - sudo apt-get -qq install
    libmysqlcppconn-dev
    yasm
    python3.6
    python3.6-dev
    libmariadbclient-dev
    sshpass
  # Cryptopp
  - wget --quiet https://cryptopp.com/cryptopp600.zip
  - unzip --qq -n -a -d cryptopp cryptopp600.zip
  - make -C cryptopp
  - sudo mkdir /usr/include/cryptopp
  - sudo mv cryptopp/*.h /usr/include/cryptopp/
  - sudo mv cryptopp/libcryptopp.a /usr/lib/

install:
  - eval "${MATRIX_EVAL}"
  - make -C pruebas_librerias
  - make -C implementaciones
  - make -C implementaciones binarios/lovelace
  - make -C implementaciones binarios/pruebas_desempenio
  - make -C utilidades
  # Base de datos
  - cd bases_de_datos
  - chmod 770 crear_base.sh
  - sudo ./crear_base.sh
  - cd ..
  - virtualenv -p /usr/bin/python3.6 entorno_virtual
  - source entorno_virtual/bin/activate
  - pip install -r dependencias_python.txt
  - python administrar.py makemigrations general programa_tokenizador
  - python administrar.py migrate
  - python bases_de_datos/datos_base.py
  - python bases_de_datos/datos_de_prueba.py

script:
  - eval "${MATRIX_EVAL}"
  - make -C implementaciones correr
  - make -C utilidades correr
  - cd implementaciones
  - chmod 770 lovelace_prueba.sh
  - ./lovelace_prueba.sh 100
  - cd ..
  - bash -v travis/pruebas_desempenio.sh

after_success:
  - sshpass -p $CONTRASENIA_SERVIDOR -o StrictHostKeyChecking=no
    ssh ricardo@ricardo-quezada.159.65.96.59.xip.io
    "cd proyecto_lovelace && ./travis/script_de_despliegue.sh $GITHUB_TOKEN $CONTRASENIA_SERVIDOR"
