#
# Archivo de configuración de Travis.
# Proyecto Lovelace.
#

# Instalación de dependencias
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
    texlive
    texlive-latex-recommended
    texlive-latex-extra
    texlive-lang-spanish
    texlive-bibtex-extra
    biber
    hunspell
    myspell-es

# Fase de construcción
script:

  # Compilación de archivos de LaTeX
  - make -C documentos_entregables
#  - make -C documentos_entregables referencias
#  - make -C documentos_entregables

  # Revisión de ortografía
#  - make -C documentos_entregables ortografía
